/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'
import type { CreateFileRoute, FileRoutesByPath } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotRouteImport } from './routes/forgot'
import { Route as PrivateLayoutRouteImport } from './routes/_privateLayout'
import { Route as PrivateLayoutIndexRouteImport } from './routes/_privateLayout/index'
import { Route as VerifyEmailVerificationCodeRouteImport } from './routes/verifyEmail.$verificationCode'
import { Route as ResetPasswordResetCodeRouteImport } from './routes/resetPassword.$resetCode'
import { Route as DetailImageTweetIdRouteImport } from './routes/detailImage.$tweetId'
import { Route as PrivateLayoutSearchRouteImport } from './routes/_privateLayout/search'
import { Route as PrivateLayoutProfileProfileLayoutRouteImport } from './routes/_privateLayout/profile/_profileLayout'
import { Route as PrivateLayoutDetailTweetTweetIdRouteImport } from './routes/_privateLayout/detailTweet.$tweetId'
import { Route as PrivateLayoutFollowsFollowsLayoutRouteImport } from './routes/_privateLayout/_follows/_followsLayout'
import { Route as PrivateLayoutProfileProfileLayoutIndexRouteImport } from './routes/_privateLayout/profile/_profileLayout/index'
import { Route as PrivateLayoutProfileProfileLayoutMediaRouteImport } from './routes/_privateLayout/profile/_profileLayout/media'
import { Route as PrivateLayoutProfileProfileIdProfileIdLayoutRouteImport } from './routes/_privateLayout/profile/$profileId/_$profileIdLayout'
import { Route as PrivateLayoutFollowsFollowsLayoutFollowingsRouteImport } from './routes/_privateLayout/_follows/_followsLayout/followings'
import { Route as PrivateLayoutFollowsFollowsLayoutFollowersRouteImport } from './routes/_privateLayout/_follows/_followsLayout/followers'
import { Route as PrivateLayoutProfileProfileIdProfileIdLayoutIndexRouteImport } from './routes/_privateLayout/profile/$profileId/_$profileIdLayout/index'
import { Route as PrivateLayoutProfileProfileIdProfileIdLayoutMediaRouteImport } from './routes/_privateLayout/profile/$profileId/_$profileIdLayout/media'

const PrivateLayoutProfileRouteImport = createFileRoute(
  '/_privateLayout/profile',
)()
const PrivateLayoutProfileProfileIdRouteImport = createFileRoute(
  '/_privateLayout/profile/$profileId',
)()

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotRoute = ForgotRouteImport.update({
  id: '/forgot',
  path: '/forgot',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivateLayoutRoute = PrivateLayoutRouteImport.update({
  id: '/_privateLayout',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivateLayoutProfileRoute = PrivateLayoutProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => PrivateLayoutRoute,
} as any)
const PrivateLayoutIndexRoute = PrivateLayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PrivateLayoutRoute,
} as any)
const VerifyEmailVerificationCodeRoute =
  VerifyEmailVerificationCodeRouteImport.update({
    id: '/verifyEmail/$verificationCode',
    path: '/verifyEmail/$verificationCode',
    getParentRoute: () => rootRouteImport,
  } as any)
const ResetPasswordResetCodeRoute = ResetPasswordResetCodeRouteImport.update({
  id: '/resetPassword/$resetCode',
  path: '/resetPassword/$resetCode',
  getParentRoute: () => rootRouteImport,
} as any)
const DetailImageTweetIdRoute = DetailImageTweetIdRouteImport.update({
  id: '/detailImage/$tweetId',
  path: '/detailImage/$tweetId',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivateLayoutSearchRoute = PrivateLayoutSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => PrivateLayoutRoute,
} as any)
const PrivateLayoutProfileProfileIdRoute =
  PrivateLayoutProfileProfileIdRouteImport.update({
    id: '/$profileId',
    path: '/$profileId',
    getParentRoute: () => PrivateLayoutProfileRoute,
  } as any)
const PrivateLayoutProfileProfileLayoutRoute =
  PrivateLayoutProfileProfileLayoutRouteImport.update({
    id: '/_profileLayout',
    getParentRoute: () => PrivateLayoutProfileRoute,
  } as any)
const PrivateLayoutDetailTweetTweetIdRoute =
  PrivateLayoutDetailTweetTweetIdRouteImport.update({
    id: '/detailTweet/$tweetId',
    path: '/detailTweet/$tweetId',
    getParentRoute: () => PrivateLayoutRoute,
  } as any)
const PrivateLayoutFollowsFollowsLayoutRoute =
  PrivateLayoutFollowsFollowsLayoutRouteImport.update({
    id: '/_follows/_followsLayout',
    getParentRoute: () => PrivateLayoutRoute,
  } as any)
const PrivateLayoutProfileProfileLayoutIndexRoute =
  PrivateLayoutProfileProfileLayoutIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => PrivateLayoutProfileProfileLayoutRoute,
  } as any)
const PrivateLayoutProfileProfileLayoutMediaRoute =
  PrivateLayoutProfileProfileLayoutMediaRouteImport.update({
    id: '/media',
    path: '/media',
    getParentRoute: () => PrivateLayoutProfileProfileLayoutRoute,
  } as any)
const PrivateLayoutProfileProfileIdProfileIdLayoutRoute =
  PrivateLayoutProfileProfileIdProfileIdLayoutRouteImport.update({
    id: '/_$profileIdLayout',
    getParentRoute: () => PrivateLayoutProfileProfileIdRoute,
  } as any)
const PrivateLayoutFollowsFollowsLayoutFollowingsRoute =
  PrivateLayoutFollowsFollowsLayoutFollowingsRouteImport.update({
    id: '/followings',
    path: '/followings',
    getParentRoute: () => PrivateLayoutFollowsFollowsLayoutRoute,
  } as any)
const PrivateLayoutFollowsFollowsLayoutFollowersRoute =
  PrivateLayoutFollowsFollowsLayoutFollowersRouteImport.update({
    id: '/followers',
    path: '/followers',
    getParentRoute: () => PrivateLayoutFollowsFollowsLayoutRoute,
  } as any)
const PrivateLayoutProfileProfileIdProfileIdLayoutIndexRoute =
  PrivateLayoutProfileProfileIdProfileIdLayoutIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => PrivateLayoutProfileProfileIdProfileIdLayoutRoute,
  } as any)
const PrivateLayoutProfileProfileIdProfileIdLayoutMediaRoute =
  PrivateLayoutProfileProfileIdProfileIdLayoutMediaRouteImport.update({
    id: '/media',
    path: '/media',
    getParentRoute: () => PrivateLayoutProfileProfileIdProfileIdLayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '': typeof PrivateLayoutFollowsFollowsLayoutRouteWithChildren
  '/forgot': typeof ForgotRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/search': typeof PrivateLayoutSearchRoute
  '/detailImage/$tweetId': typeof DetailImageTweetIdRoute
  '/resetPassword/$resetCode': typeof ResetPasswordResetCodeRoute
  '/verifyEmail/$verificationCode': typeof VerifyEmailVerificationCodeRoute
  '/': typeof PrivateLayoutIndexRoute
  '/detailTweet/$tweetId': typeof PrivateLayoutDetailTweetTweetIdRoute
  '/profile': typeof PrivateLayoutProfileProfileLayoutRouteWithChildren
  '/followers': typeof PrivateLayoutFollowsFollowsLayoutFollowersRoute
  '/followings': typeof PrivateLayoutFollowsFollowsLayoutFollowingsRoute
  '/profile/$profileId': typeof PrivateLayoutProfileProfileIdProfileIdLayoutRouteWithChildren
  '/profile/media': typeof PrivateLayoutProfileProfileLayoutMediaRoute
  '/profile/': typeof PrivateLayoutProfileProfileLayoutIndexRoute
  '/profile/$profileId/media': typeof PrivateLayoutProfileProfileIdProfileIdLayoutMediaRoute
  '/profile/$profileId/': typeof PrivateLayoutProfileProfileIdProfileIdLayoutIndexRoute
}
export interface FileRoutesByTo {
  '/forgot': typeof ForgotRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/search': typeof PrivateLayoutSearchRoute
  '/detailImage/$tweetId': typeof DetailImageTweetIdRoute
  '/resetPassword/$resetCode': typeof ResetPasswordResetCodeRoute
  '/verifyEmail/$verificationCode': typeof VerifyEmailVerificationCodeRoute
  '/': typeof PrivateLayoutIndexRoute
  '': typeof PrivateLayoutFollowsFollowsLayoutRouteWithChildren
  '/detailTweet/$tweetId': typeof PrivateLayoutDetailTweetTweetIdRoute
  '/profile': typeof PrivateLayoutProfileProfileLayoutIndexRoute
  '/followers': typeof PrivateLayoutFollowsFollowsLayoutFollowersRoute
  '/followings': typeof PrivateLayoutFollowsFollowsLayoutFollowingsRoute
  '/profile/$profileId': typeof PrivateLayoutProfileProfileIdProfileIdLayoutIndexRoute
  '/profile/media': typeof PrivateLayoutProfileProfileLayoutMediaRoute
  '/profile/$profileId/media': typeof PrivateLayoutProfileProfileIdProfileIdLayoutMediaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_privateLayout': typeof PrivateLayoutRouteWithChildren
  '/forgot': typeof ForgotRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/_privateLayout/search': typeof PrivateLayoutSearchRoute
  '/detailImage/$tweetId': typeof DetailImageTweetIdRoute
  '/resetPassword/$resetCode': typeof ResetPasswordResetCodeRoute
  '/verifyEmail/$verificationCode': typeof VerifyEmailVerificationCodeRoute
  '/_privateLayout/': typeof PrivateLayoutIndexRoute
  '/_privateLayout/_follows/_followsLayout': typeof PrivateLayoutFollowsFollowsLayoutRouteWithChildren
  '/_privateLayout/detailTweet/$tweetId': typeof PrivateLayoutDetailTweetTweetIdRoute
  '/_privateLayout/profile': typeof PrivateLayoutProfileRouteWithChildren
  '/_privateLayout/profile/_profileLayout': typeof PrivateLayoutProfileProfileLayoutRouteWithChildren
  '/_privateLayout/_follows/_followsLayout/followers': typeof PrivateLayoutFollowsFollowsLayoutFollowersRoute
  '/_privateLayout/_follows/_followsLayout/followings': typeof PrivateLayoutFollowsFollowsLayoutFollowingsRoute
  '/_privateLayout/profile/$profileId': typeof PrivateLayoutProfileProfileIdRouteWithChildren
  '/_privateLayout/profile/$profileId/_$profileIdLayout': typeof PrivateLayoutProfileProfileIdProfileIdLayoutRouteWithChildren
  '/_privateLayout/profile/_profileLayout/media': typeof PrivateLayoutProfileProfileLayoutMediaRoute
  '/_privateLayout/profile/_profileLayout/': typeof PrivateLayoutProfileProfileLayoutIndexRoute
  '/_privateLayout/profile/$profileId/_$profileIdLayout/media': typeof PrivateLayoutProfileProfileIdProfileIdLayoutMediaRoute
  '/_privateLayout/profile/$profileId/_$profileIdLayout/': typeof PrivateLayoutProfileProfileIdProfileIdLayoutIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | ''
    | '/forgot'
    | '/login'
    | '/register'
    | '/search'
    | '/detailImage/$tweetId'
    | '/resetPassword/$resetCode'
    | '/verifyEmail/$verificationCode'
    | '/'
    | '/detailTweet/$tweetId'
    | '/profile'
    | '/followers'
    | '/followings'
    | '/profile/$profileId'
    | '/profile/media'
    | '/profile/'
    | '/profile/$profileId/media'
    | '/profile/$profileId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/forgot'
    | '/login'
    | '/register'
    | '/search'
    | '/detailImage/$tweetId'
    | '/resetPassword/$resetCode'
    | '/verifyEmail/$verificationCode'
    | '/'
    | ''
    | '/detailTweet/$tweetId'
    | '/profile'
    | '/followers'
    | '/followings'
    | '/profile/$profileId'
    | '/profile/media'
    | '/profile/$profileId/media'
  id:
    | '__root__'
    | '/_privateLayout'
    | '/forgot'
    | '/login'
    | '/register'
    | '/_privateLayout/search'
    | '/detailImage/$tweetId'
    | '/resetPassword/$resetCode'
    | '/verifyEmail/$verificationCode'
    | '/_privateLayout/'
    | '/_privateLayout/_follows/_followsLayout'
    | '/_privateLayout/detailTweet/$tweetId'
    | '/_privateLayout/profile'
    | '/_privateLayout/profile/_profileLayout'
    | '/_privateLayout/_follows/_followsLayout/followers'
    | '/_privateLayout/_follows/_followsLayout/followings'
    | '/_privateLayout/profile/$profileId'
    | '/_privateLayout/profile/$profileId/_$profileIdLayout'
    | '/_privateLayout/profile/_profileLayout/media'
    | '/_privateLayout/profile/_profileLayout/'
    | '/_privateLayout/profile/$profileId/_$profileIdLayout/media'
    | '/_privateLayout/profile/$profileId/_$profileIdLayout/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  PrivateLayoutRoute: typeof PrivateLayoutRouteWithChildren
  ForgotRoute: typeof ForgotRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  DetailImageTweetIdRoute: typeof DetailImageTweetIdRoute
  ResetPasswordResetCodeRoute: typeof ResetPasswordResetCodeRoute
  VerifyEmailVerificationCodeRoute: typeof VerifyEmailVerificationCodeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_privateLayout': {
      id: '/_privateLayout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof PrivateLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot': {
      id: '/forgot'
      path: '/forgot'
      fullPath: '/forgot'
      preLoaderRoute: typeof ForgotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_privateLayout/search': {
      id: '/_privateLayout/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof PrivateLayoutSearchRouteImport
      parentRoute: typeof PrivateLayoutRoute
    }
    '/detailImage/$tweetId': {
      id: '/detailImage/$tweetId'
      path: '/detailImage/$tweetId'
      fullPath: '/detailImage/$tweetId'
      preLoaderRoute: typeof DetailImageTweetIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resetPassword/$resetCode': {
      id: '/resetPassword/$resetCode'
      path: '/resetPassword/$resetCode'
      fullPath: '/resetPassword/$resetCode'
      preLoaderRoute: typeof ResetPasswordResetCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verifyEmail/$verificationCode': {
      id: '/verifyEmail/$verificationCode'
      path: '/verifyEmail/$verificationCode'
      fullPath: '/verifyEmail/$verificationCode'
      preLoaderRoute: typeof VerifyEmailVerificationCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_privateLayout/': {
      id: '/_privateLayout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PrivateLayoutIndexRouteImport
      parentRoute: typeof PrivateLayoutRoute
    }
    '/_privateLayout/_follows/_followsLayout': {
      id: '/_privateLayout/_follows/_followsLayout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof PrivateLayoutFollowsFollowsLayoutRouteImport
      parentRoute: typeof PrivateLayoutRoute
    }
    '/_privateLayout/detailTweet/$tweetId': {
      id: '/_privateLayout/detailTweet/$tweetId'
      path: '/detailTweet/$tweetId'
      fullPath: '/detailTweet/$tweetId'
      preLoaderRoute: typeof PrivateLayoutDetailTweetTweetIdRouteImport
      parentRoute: typeof PrivateLayoutRoute
    }
    '/_privateLayout/profile/_profileLayout': {
      id: '/_privateLayout/profile/_profileLayout'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof PrivateLayoutProfileProfileLayoutRouteImport
      parentRoute: typeof PrivateLayoutProfileRoute
    }
    '/_privateLayout/_follows/_followsLayout/followers': {
      id: '/_privateLayout/_follows/_followsLayout/followers'
      path: '/followers'
      fullPath: '/followers'
      preLoaderRoute: typeof PrivateLayoutFollowsFollowsLayoutFollowersRouteImport
      parentRoute: typeof PrivateLayoutFollowsFollowsLayoutRoute
    }
    '/_privateLayout/_follows/_followsLayout/followings': {
      id: '/_privateLayout/_follows/_followsLayout/followings'
      path: '/followings'
      fullPath: '/followings'
      preLoaderRoute: typeof PrivateLayoutFollowsFollowsLayoutFollowingsRouteImport
      parentRoute: typeof PrivateLayoutFollowsFollowsLayoutRoute
    }
    '/_privateLayout/profile/$profileId/_$profileIdLayout': {
      id: '/_privateLayout/profile/$profileId/_$profileIdLayout'
      path: '/$profileId'
      fullPath: '/profile/$profileId'
      preLoaderRoute: typeof PrivateLayoutProfileProfileIdProfileIdLayoutRouteImport
      parentRoute: typeof PrivateLayoutProfileProfileIdRoute
    }
    '/_privateLayout/profile/_profileLayout/media': {
      id: '/_privateLayout/profile/_profileLayout/media'
      path: '/media'
      fullPath: '/profile/media'
      preLoaderRoute: typeof PrivateLayoutProfileProfileLayoutMediaRouteImport
      parentRoute: typeof PrivateLayoutProfileProfileLayoutRoute
    }
    '/_privateLayout/profile/_profileLayout/': {
      id: '/_privateLayout/profile/_profileLayout/'
      path: '/'
      fullPath: '/profile/'
      preLoaderRoute: typeof PrivateLayoutProfileProfileLayoutIndexRouteImport
      parentRoute: typeof PrivateLayoutProfileProfileLayoutRoute
    }
    '/_privateLayout/profile/$profileId/_$profileIdLayout/media': {
      id: '/_privateLayout/profile/$profileId/_$profileIdLayout/media'
      path: '/media'
      fullPath: '/profile/$profileId/media'
      preLoaderRoute: typeof PrivateLayoutProfileProfileIdProfileIdLayoutMediaRouteImport
      parentRoute: typeof PrivateLayoutProfileProfileIdProfileIdLayoutRoute
    }
    '/_privateLayout/profile/$profileId/_$profileIdLayout/': {
      id: '/_privateLayout/profile/$profileId/_$profileIdLayout/'
      path: '/'
      fullPath: '/profile/$profileId/'
      preLoaderRoute: typeof PrivateLayoutProfileProfileIdProfileIdLayoutIndexRouteImport
      parentRoute: typeof PrivateLayoutProfileProfileIdProfileIdLayoutRoute
    }
    '/_privateLayout/profile': {
      id: '/_privateLayout/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof PrivateLayoutProfileRouteImport
      parentRoute: typeof PrivateLayoutRoute
    }
    '/_privateLayout/profile/$profileId': {
      id: '/_privateLayout/profile/$profileId'
      path: '/$profileId'
      fullPath: '/profile/$profileId'
      preLoaderRoute: typeof PrivateLayoutProfileProfileIdRouteImport
      parentRoute: typeof PrivateLayoutProfileRoute
    }
  }
}

declare module './routes/_privateLayout' {
  const createFileRoute: CreateFileRoute<
    '/_privateLayout',
    FileRoutesByPath['/_privateLayout']['parentRoute'],
    FileRoutesByPath['/_privateLayout']['id'],
    FileRoutesByPath['/_privateLayout']['path'],
    FileRoutesByPath['/_privateLayout']['fullPath']
  >
}
declare module './routes/forgot' {
  const createFileRoute: CreateFileRoute<
    '/forgot',
    FileRoutesByPath['/forgot']['parentRoute'],
    FileRoutesByPath['/forgot']['id'],
    FileRoutesByPath['/forgot']['path'],
    FileRoutesByPath['/forgot']['fullPath']
  >
}
declare module './routes/login' {
  const createFileRoute: CreateFileRoute<
    '/login',
    FileRoutesByPath['/login']['parentRoute'],
    FileRoutesByPath['/login']['id'],
    FileRoutesByPath['/login']['path'],
    FileRoutesByPath['/login']['fullPath']
  >
}
declare module './routes/register' {
  const createFileRoute: CreateFileRoute<
    '/register',
    FileRoutesByPath['/register']['parentRoute'],
    FileRoutesByPath['/register']['id'],
    FileRoutesByPath['/register']['path'],
    FileRoutesByPath['/register']['fullPath']
  >
}
declare module './routes/_privateLayout/search' {
  const createFileRoute: CreateFileRoute<
    '/_privateLayout/search',
    FileRoutesByPath['/_privateLayout/search']['parentRoute'],
    FileRoutesByPath['/_privateLayout/search']['id'],
    FileRoutesByPath['/_privateLayout/search']['path'],
    FileRoutesByPath['/_privateLayout/search']['fullPath']
  >
}
declare module './routes/detailImage.$tweetId' {
  const createFileRoute: CreateFileRoute<
    '/detailImage/$tweetId',
    FileRoutesByPath['/detailImage/$tweetId']['parentRoute'],
    FileRoutesByPath['/detailImage/$tweetId']['id'],
    FileRoutesByPath['/detailImage/$tweetId']['path'],
    FileRoutesByPath['/detailImage/$tweetId']['fullPath']
  >
}
declare module './routes/resetPassword.$resetCode' {
  const createFileRoute: CreateFileRoute<
    '/resetPassword/$resetCode',
    FileRoutesByPath['/resetPassword/$resetCode']['parentRoute'],
    FileRoutesByPath['/resetPassword/$resetCode']['id'],
    FileRoutesByPath['/resetPassword/$resetCode']['path'],
    FileRoutesByPath['/resetPassword/$resetCode']['fullPath']
  >
}
declare module './routes/verifyEmail.$verificationCode' {
  const createFileRoute: CreateFileRoute<
    '/verifyEmail/$verificationCode',
    FileRoutesByPath['/verifyEmail/$verificationCode']['parentRoute'],
    FileRoutesByPath['/verifyEmail/$verificationCode']['id'],
    FileRoutesByPath['/verifyEmail/$verificationCode']['path'],
    FileRoutesByPath['/verifyEmail/$verificationCode']['fullPath']
  >
}
declare module './routes/_privateLayout/index' {
  const createFileRoute: CreateFileRoute<
    '/_privateLayout/',
    FileRoutesByPath['/_privateLayout/']['parentRoute'],
    FileRoutesByPath['/_privateLayout/']['id'],
    FileRoutesByPath['/_privateLayout/']['path'],
    FileRoutesByPath['/_privateLayout/']['fullPath']
  >
}
declare module './routes/_privateLayout/_follows/_followsLayout' {
  const createFileRoute: CreateFileRoute<
    '/_privateLayout/_follows/_followsLayout',
    FileRoutesByPath['/_privateLayout/_follows/_followsLayout']['parentRoute'],
    FileRoutesByPath['/_privateLayout/_follows/_followsLayout']['id'],
    FileRoutesByPath['/_privateLayout/_follows/_followsLayout']['path'],
    FileRoutesByPath['/_privateLayout/_follows/_followsLayout']['fullPath']
  >
}
declare module './routes/_privateLayout/detailTweet.$tweetId' {
  const createFileRoute: CreateFileRoute<
    '/_privateLayout/detailTweet/$tweetId',
    FileRoutesByPath['/_privateLayout/detailTweet/$tweetId']['parentRoute'],
    FileRoutesByPath['/_privateLayout/detailTweet/$tweetId']['id'],
    FileRoutesByPath['/_privateLayout/detailTweet/$tweetId']['path'],
    FileRoutesByPath['/_privateLayout/detailTweet/$tweetId']['fullPath']
  >
}
declare module './routes/_privateLayout/profile/_profileLayout' {
  const createFileRoute: CreateFileRoute<
    '/_privateLayout/profile/_profileLayout',
    FileRoutesByPath['/_privateLayout/profile/_profileLayout']['parentRoute'],
    FileRoutesByPath['/_privateLayout/profile/_profileLayout']['id'],
    FileRoutesByPath['/_privateLayout/profile/_profileLayout']['path'],
    FileRoutesByPath['/_privateLayout/profile/_profileLayout']['fullPath']
  >
}
declare module './routes/_privateLayout/_follows/_followsLayout/followers' {
  const createFileRoute: CreateFileRoute<
    '/_privateLayout/_follows/_followsLayout/followers',
    FileRoutesByPath['/_privateLayout/_follows/_followsLayout/followers']['parentRoute'],
    FileRoutesByPath['/_privateLayout/_follows/_followsLayout/followers']['id'],
    FileRoutesByPath['/_privateLayout/_follows/_followsLayout/followers']['path'],
    FileRoutesByPath['/_privateLayout/_follows/_followsLayout/followers']['fullPath']
  >
}
declare module './routes/_privateLayout/_follows/_followsLayout/followings' {
  const createFileRoute: CreateFileRoute<
    '/_privateLayout/_follows/_followsLayout/followings',
    FileRoutesByPath['/_privateLayout/_follows/_followsLayout/followings']['parentRoute'],
    FileRoutesByPath['/_privateLayout/_follows/_followsLayout/followings']['id'],
    FileRoutesByPath['/_privateLayout/_follows/_followsLayout/followings']['path'],
    FileRoutesByPath['/_privateLayout/_follows/_followsLayout/followings']['fullPath']
  >
}
declare module './routes/_privateLayout/profile/$profileId/_$profileIdLayout' {
  const createFileRoute: CreateFileRoute<
    '/_privateLayout/profile/$profileId/_$profileIdLayout',
    FileRoutesByPath['/_privateLayout/profile/$profileId/_$profileIdLayout']['parentRoute'],
    FileRoutesByPath['/_privateLayout/profile/$profileId/_$profileIdLayout']['id'],
    FileRoutesByPath['/_privateLayout/profile/$profileId/_$profileIdLayout']['path'],
    FileRoutesByPath['/_privateLayout/profile/$profileId/_$profileIdLayout']['fullPath']
  >
}
declare module './routes/_privateLayout/profile/_profileLayout/media' {
  const createFileRoute: CreateFileRoute<
    '/_privateLayout/profile/_profileLayout/media',
    FileRoutesByPath['/_privateLayout/profile/_profileLayout/media']['parentRoute'],
    FileRoutesByPath['/_privateLayout/profile/_profileLayout/media']['id'],
    FileRoutesByPath['/_privateLayout/profile/_profileLayout/media']['path'],
    FileRoutesByPath['/_privateLayout/profile/_profileLayout/media']['fullPath']
  >
}
declare module './routes/_privateLayout/profile/_profileLayout/index' {
  const createFileRoute: CreateFileRoute<
    '/_privateLayout/profile/_profileLayout/',
    FileRoutesByPath['/_privateLayout/profile/_profileLayout/']['parentRoute'],
    FileRoutesByPath['/_privateLayout/profile/_profileLayout/']['id'],
    FileRoutesByPath['/_privateLayout/profile/_profileLayout/']['path'],
    FileRoutesByPath['/_privateLayout/profile/_profileLayout/']['fullPath']
  >
}
declare module './routes/_privateLayout/profile/$profileId/_$profileIdLayout/media' {
  const createFileRoute: CreateFileRoute<
    '/_privateLayout/profile/$profileId/_$profileIdLayout/media',
    FileRoutesByPath['/_privateLayout/profile/$profileId/_$profileIdLayout/media']['parentRoute'],
    FileRoutesByPath['/_privateLayout/profile/$profileId/_$profileIdLayout/media']['id'],
    FileRoutesByPath['/_privateLayout/profile/$profileId/_$profileIdLayout/media']['path'],
    FileRoutesByPath['/_privateLayout/profile/$profileId/_$profileIdLayout/media']['fullPath']
  >
}
declare module './routes/_privateLayout/profile/$profileId/_$profileIdLayout/index' {
  const createFileRoute: CreateFileRoute<
    '/_privateLayout/profile/$profileId/_$profileIdLayout/',
    FileRoutesByPath['/_privateLayout/profile/$profileId/_$profileIdLayout/']['parentRoute'],
    FileRoutesByPath['/_privateLayout/profile/$profileId/_$profileIdLayout/']['id'],
    FileRoutesByPath['/_privateLayout/profile/$profileId/_$profileIdLayout/']['path'],
    FileRoutesByPath['/_privateLayout/profile/$profileId/_$profileIdLayout/']['fullPath']
  >
}

interface PrivateLayoutFollowsFollowsLayoutRouteChildren {
  PrivateLayoutFollowsFollowsLayoutFollowersRoute: typeof PrivateLayoutFollowsFollowsLayoutFollowersRoute
  PrivateLayoutFollowsFollowsLayoutFollowingsRoute: typeof PrivateLayoutFollowsFollowsLayoutFollowingsRoute
}

const PrivateLayoutFollowsFollowsLayoutRouteChildren: PrivateLayoutFollowsFollowsLayoutRouteChildren =
  {
    PrivateLayoutFollowsFollowsLayoutFollowersRoute:
      PrivateLayoutFollowsFollowsLayoutFollowersRoute,
    PrivateLayoutFollowsFollowsLayoutFollowingsRoute:
      PrivateLayoutFollowsFollowsLayoutFollowingsRoute,
  }

const PrivateLayoutFollowsFollowsLayoutRouteWithChildren =
  PrivateLayoutFollowsFollowsLayoutRoute._addFileChildren(
    PrivateLayoutFollowsFollowsLayoutRouteChildren,
  )

interface PrivateLayoutProfileProfileLayoutRouteChildren {
  PrivateLayoutProfileProfileLayoutMediaRoute: typeof PrivateLayoutProfileProfileLayoutMediaRoute
  PrivateLayoutProfileProfileLayoutIndexRoute: typeof PrivateLayoutProfileProfileLayoutIndexRoute
}

const PrivateLayoutProfileProfileLayoutRouteChildren: PrivateLayoutProfileProfileLayoutRouteChildren =
  {
    PrivateLayoutProfileProfileLayoutMediaRoute:
      PrivateLayoutProfileProfileLayoutMediaRoute,
    PrivateLayoutProfileProfileLayoutIndexRoute:
      PrivateLayoutProfileProfileLayoutIndexRoute,
  }

const PrivateLayoutProfileProfileLayoutRouteWithChildren =
  PrivateLayoutProfileProfileLayoutRoute._addFileChildren(
    PrivateLayoutProfileProfileLayoutRouteChildren,
  )

interface PrivateLayoutProfileProfileIdProfileIdLayoutRouteChildren {
  PrivateLayoutProfileProfileIdProfileIdLayoutMediaRoute: typeof PrivateLayoutProfileProfileIdProfileIdLayoutMediaRoute
  PrivateLayoutProfileProfileIdProfileIdLayoutIndexRoute: typeof PrivateLayoutProfileProfileIdProfileIdLayoutIndexRoute
}

const PrivateLayoutProfileProfileIdProfileIdLayoutRouteChildren: PrivateLayoutProfileProfileIdProfileIdLayoutRouteChildren =
  {
    PrivateLayoutProfileProfileIdProfileIdLayoutMediaRoute:
      PrivateLayoutProfileProfileIdProfileIdLayoutMediaRoute,
    PrivateLayoutProfileProfileIdProfileIdLayoutIndexRoute:
      PrivateLayoutProfileProfileIdProfileIdLayoutIndexRoute,
  }

const PrivateLayoutProfileProfileIdProfileIdLayoutRouteWithChildren =
  PrivateLayoutProfileProfileIdProfileIdLayoutRoute._addFileChildren(
    PrivateLayoutProfileProfileIdProfileIdLayoutRouteChildren,
  )

interface PrivateLayoutProfileProfileIdRouteChildren {
  PrivateLayoutProfileProfileIdProfileIdLayoutRoute: typeof PrivateLayoutProfileProfileIdProfileIdLayoutRouteWithChildren
}

const PrivateLayoutProfileProfileIdRouteChildren: PrivateLayoutProfileProfileIdRouteChildren =
  {
    PrivateLayoutProfileProfileIdProfileIdLayoutRoute:
      PrivateLayoutProfileProfileIdProfileIdLayoutRouteWithChildren,
  }

const PrivateLayoutProfileProfileIdRouteWithChildren =
  PrivateLayoutProfileProfileIdRoute._addFileChildren(
    PrivateLayoutProfileProfileIdRouteChildren,
  )

interface PrivateLayoutProfileRouteChildren {
  PrivateLayoutProfileProfileLayoutRoute: typeof PrivateLayoutProfileProfileLayoutRouteWithChildren
  PrivateLayoutProfileProfileIdRoute: typeof PrivateLayoutProfileProfileIdRouteWithChildren
}

const PrivateLayoutProfileRouteChildren: PrivateLayoutProfileRouteChildren = {
  PrivateLayoutProfileProfileLayoutRoute:
    PrivateLayoutProfileProfileLayoutRouteWithChildren,
  PrivateLayoutProfileProfileIdRoute:
    PrivateLayoutProfileProfileIdRouteWithChildren,
}

const PrivateLayoutProfileRouteWithChildren =
  PrivateLayoutProfileRoute._addFileChildren(PrivateLayoutProfileRouteChildren)

interface PrivateLayoutRouteChildren {
  PrivateLayoutSearchRoute: typeof PrivateLayoutSearchRoute
  PrivateLayoutIndexRoute: typeof PrivateLayoutIndexRoute
  PrivateLayoutFollowsFollowsLayoutRoute: typeof PrivateLayoutFollowsFollowsLayoutRouteWithChildren
  PrivateLayoutDetailTweetTweetIdRoute: typeof PrivateLayoutDetailTweetTweetIdRoute
  PrivateLayoutProfileRoute: typeof PrivateLayoutProfileRouteWithChildren
}

const PrivateLayoutRouteChildren: PrivateLayoutRouteChildren = {
  PrivateLayoutSearchRoute: PrivateLayoutSearchRoute,
  PrivateLayoutIndexRoute: PrivateLayoutIndexRoute,
  PrivateLayoutFollowsFollowsLayoutRoute:
    PrivateLayoutFollowsFollowsLayoutRouteWithChildren,
  PrivateLayoutDetailTweetTweetIdRoute: PrivateLayoutDetailTweetTweetIdRoute,
  PrivateLayoutProfileRoute: PrivateLayoutProfileRouteWithChildren,
}

const PrivateLayoutRouteWithChildren = PrivateLayoutRoute._addFileChildren(
  PrivateLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  PrivateLayoutRoute: PrivateLayoutRouteWithChildren,
  ForgotRoute: ForgotRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  DetailImageTweetIdRoute: DetailImageTweetIdRoute,
  ResetPasswordResetCodeRoute: ResetPasswordResetCodeRoute,
  VerifyEmailVerificationCodeRoute: VerifyEmailVerificationCodeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
